---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --user aws-sam-cli
  build:
    commands:
      - cd sam-app
      - export PATH=$PATH:/root/.local/bin
      - make build
      - make package
artifacts:
  type: zip
  files:
    - sam-app/output.yml
  discard-paths: yes
