---
version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - cd sam-app
      - make build
      - make package
artifacts:
  type: zip
  files:
    - output.yml
